/* eslint-disable @typescript-eslint/comma-dangle */
export enum PharmaceuticalEstablishmentActionTypes {
  SET_ESTABLISHMENT_INFORMATION = "SET_ESTABLISHMENT_INFORMATION",
  SET_CONTACT_INFORMATION = "SET_CONTACT_INFORMATION",
  SET_LOACTION_INFORMATION = "SET_LOACTION_INFORMATION",
  SET_OWNER_DETAILS = "SET_OWNER_DETAILS",
  SET_PARTNER_DETAILS = "SET_PARTNER_DETAILS",
  SET_SELF_EVALUATION = "SET_SELF_EVALUATION",
  SET_STEP_NUMBER = "SET_STEP_NUMBER",
  NEXT_STEP_NUMBER= "NEXT_STEP_NUMBER",
  SET_PROGRESS_PERSENTAGE = "SET_PROGRESS_PERSENTAGE",


}
