export enum PharmaceuticalEstablishmentActionTypes {
  SET_ESTABLISHMENT_INFORMATION = "SET_ESTABLISHMENT_INFORMATION",
  SET_CONTACT_INFORMATION = "SET_CONTACT_INFORMATION",
  SET_LOACTION_INFORMATION = "SET_LOACTION_INFORMATION",
  SET_OWNER_DETAILS = "SET_OWNER_DETAILS",
  SET_PARTNER_DETAILS = "SET_PARTNER_DETAILS",
  Add_New_PARTNER = "Add_New_PARTNER",
  EDIT_PARTNER = "EDIT_PARTNER",
  Remove_New_PARTNER = "Remove_New_PARTNER",
  SET_SELF_EVALUATION = "SET_SELF_EVALUATION",
  SET_STEP_NUMBER = "SET_STEP_NUMBER",
  NEXT_STEP_NUMBER = "NEXT_STEP_NUMBER",
}

export enum RelocationPharmaceuticaActionTypes {
  SET_LOACTION_INFORMATION = "SET_LOACTION_INFORMATION",
  SET_SELF_EVALUATION = "SET_SELF_EVALUATION",
  SET_STEP_NUMBER = "SET_STEP_NUMBER",
  NEXT_STEP_NUMBER = "NEXT_STEP_NUMBER",
  SET_PROGRESS_PERSENTAGE = "SET_PROGRESS_PERSENTAGE",
}

export enum LayoutActionTypes {
  SET_FOOTER_CONTENT = "SET_FOOTER_CONTENT",
  SET_INFO_DESCRIPTION = "SET_INFO_DESCRIPTION",
  SET_INFO_FEES = "SET_INFO_FEES",
  SHOW_BACK_BUTTON = "SHOW_BACK_BUTTON",
  HIDE_BACK_BUTTON = "HIDE_BACK_BUTTON",
  SHOW_INFO = "SHOW_INFO",
  HIDE_INFO = "HIDE_INFO",
  SHOW_FOOTER = "SHOW_FOOTER",
  HIDE_FOOTER = "HIDE_FOOTER",
  HIDE_FOOTER_WITH_INFO_AND_BACK_BUTTON = "HIDE_FOOTER_WITH_INFO_AND_BACK_BUTTON",
  SET_PROGRESS_PERSENTAGE = "SET_PROGRESS_PERSENTAGE",

  // breadcrumb
  SET_BREADCRUMB_TITLE = "SET_BREADCRUMB_TITLE",
}

export enum LookupsActionTypes {
  FETCH_LOOKUPS_REQUESTED = "FETCH_LOOKUPS_REQUESTED",
  FETCH_LOOKUPS_SUCCESS = "FETCH_LOOKUPS_SUCCESS",
  FETCH_LOOKUPS_FAILURE = "FETCH_LOOKUPS_FAILURE",
}
